# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d6b5d9df759b3583b32f1ec1dc57c9a4d2c2303578f30e6e3f6644239febed240d6bd4b0dad7afc4bb88ae69e83288cac94158c98664065df2e4544a55a1446

test:
  secret_key_base: 0923b8e4b94e53517772a13f87efdea93edb2b2184ec8729e724f48792833574648734e69daec57472625ee07bc57e8ec494dd3010555db93197911f10ad0341

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
